# Generated by Django 4.1.3 on 2022-12-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_image', models.ImageField(upload_to='', verbose_name='Obraz żródłowy')),
                ('search_slug', models.CharField(max_length=20, unique=True, verbose_name='Pole wuszikwania')),
            ],
        ),
    ]
