# Generated by Django 4.1.3 on 2022-11-20 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_avatar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='manager_app.avatar', verbose_name='Avatar użytkownika'),
        ),
    ]
