# Generated by Django 4.1.3 on 2022-11-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0004_alter_customuser_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='registration_datatime',
            new_name='registration_datetime',
        ),
    ]
