# Generated by Django 4.1.3 on 2022-11-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0004_column_tasksseq_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_members',
            field=models.IntegerField(default=2),
        ),
    ]
