# Generated by Django 4.1.3 on 2022-12-07 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0004_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_app.project')),
            ],
        ),
    ]

