# Generated by Django 4.1.3 on 2022-12-07 17:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0005_memberpool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_app.project')),
            ],
        ),
    ]

