# Generated by Django 4.1.3 on 2022-12-07 17:28

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0006_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksSeq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=16)),
                ('column', models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='manager_app.column')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('content', models.CharField(max_length=80)),
                ('done_status', models.BooleanField(default=False)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.column')),
            ],
        ),
    ]

