# Generated by Django 4.1.3 on 2023-01-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0010_alter_avatar_source_image_projectfiles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileExtensionIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=12, unique=True)),
                ('icon', models.ImageField(upload_to='project_files/extension_icons/')),
            ],
        ),
    ]
