# Generated by Django 4.1.3 on 2023-01-02 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0011_fileextensionicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentfile',
            name='extension_icon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='manager_app.fileextensionicon'),
        ),
    ]
