services:
  nginx:
    build: ./nginx

    volumes:
      - staticfiles:/www/static
      - mediafiles:/www/media

    ports:
     - $NGINX_EXPOSE_PORT:80

    links:
     - app

  app:
    build: ./project_manager

    # command: gunicorn project_manager.asgi:application -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000
    # daphne -b 0.0.0.0 -p 8000 project_manager.asgi:application
    # command: python manage.py runserver 0.0.0.0:8000
    # gunicorn project_manager.wsgi:application --bind 0.0.0.0:8000 --error-logfile '-'
    command: sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py default_admin &&
      python manage.py runserver 0.0.0.0:8000
      "

    volumes:
      - staticfiles:/project_manager/staticfiles
      - mediafiles:/project_manager/media

    expose:
      - 8000

    env_file:
     - .env

    links: 
     - postgres
     - redis

  postgres:
    image: postgres:15

    expose:
      - 5432

    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
    
    volumes:
      - project_manager_db:/var/lib/postgresql/data

  redis:
    image: redis

    expose:
      - 6379

    

volumes:
  project_manager_db:
  staticfiles:
  mediafiles:
      
