# Generated by Django 4.1.3 on 2022-12-07 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0002_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='manager_app.avatar', verbose_name='Avatar użytkownika'),
        ),
    ]
